### ISSUE TITLE
WDIO8 / wdio-wait-for - Condition is not a function

### ISSUE THREAD

**Issue by LordPato** [webdriverio/wdio-wait-for#343]
After updating to WDIO8 and wdio-wait-for 3.0.1 I started to get this "Condition is not a function" whenever I try to use "urlContains"

Simple code :

    import { urlContains } from 'wdio-wait-for';

    export async function crossSellHandler(option: string) {
        await basePage.waitForPageStopLoadding()
        return await browser.waitUntil(urlContains("/test/"), { timeout: 60000, timeoutMsg: "Test page is not displayed" });

Error :

    Error: Condition is not a function
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async World.crossSellHandler (...\test.ts:17:12)

Any clues where to look? The same code was properly working before updating.

FYI : It works fine with version 2.2.6

**Comment by christian-bromann** [comment]
@LordPato thanks for filing the issue. You want to help us get on the bottom of this? With `v3` we've rewritten the package to ESM which might be responsible for this. Let me know if we can help contributing to this project.

**Comment by LordPato** [comment]
The way to make it work was to add another await before the urlcontains like

import { urlContains } from 'wdio-wait-for';

export async function crossSellHandler(option: string) {
    await basePage.waitForPageStopLoadding()
    return await browser.waitUntil(**await** urlContains("/test/"), { timeout: 60000, timeoutMsg: "Test page is not displayed" });

Which doesn't seems right. For the moment I rolled it back to 2.2.6 while I have a different branch using 3.0.1 to investigate furtgher.

**Comment by christian-bromann** [comment]
It seems like the CJS export functions are written incorrect, e.g. with [`titleContains`](https://github.com/webdriverio/wdio-wait-for/blob/main/src/cjs/browser.ts#L11-L14), instead of:

```js
exports.titleContains = async function (expectedTitle: string) {
    const fn = (await importBrowserPromise).titleContains
    return fn.call(this, expectedTitle)
}
```

it should be:

```js
exports.titleContains = function (expectedTitle: string) {
  return async function (this: WebdriverIO.Browser): Promise<boolean> {
    const fn = (await importBrowserPromise).titleContains
    return fn.call(this, expectedTitle)
  }
}
```

Do you want to help us get a fix for them in place?

**Comment by LordPato** [comment]
Sure. I'll help you with it.
